import { getHealth } from "../services/health.service.js"; import { initializeAuth } from "./auth.js"; import { setState,getState } from "./state.js"; import { registerRoute,startRouter } from "./router.js"; import { renderHeader } from "../components/header.js"; import { renderSidebar } from "../components/sidebar.js"; import { renderBreadcrumb } from "../components/breadcrumb.js"; import { renderFooter } from "../components/footer.js"; import { showAlert,clearAlert } from "../components/alert.js"; import { dashboardPage } from "../pages/dashboard.js"; import { sitesPage } from "../pages/sites.js"; import { sitePage } from "../pages/site.js"; import { domainesPage } from "../pages/domaines.js"; import { pagesPage,modulesPage,mediasPage,seoPage,parametresPage,journalPage,notFoundPage } from "../pages/generic.js";
function mount(page,breadcrumb){ clearAlert(); document.querySelector("#app-sidebar").innerHTML=renderSidebar(); document.querySelector("#app-breadcrumb").innerHTML=renderBreadcrumb(breadcrumb); document.querySelector("#app-page").innerHTML=page; document.querySelector("#app-page").insertAdjacentHTML("beforeend",renderFooter()); document.querySelector("#main").focus(); }
registerRoute("/", async () => {
  const domaine = window.location.hostname
    .trim()
    .toLowerCase();

  const page = await accueilPage(domaine);

  mount(page, ["Accueil"]);
}); registerRoute("/sites",()=>mount(sitesPage(),["Cockpit","Sites"])); registerRoute("/site/:id",p=>mount(sitePage(p),["Cockpit","Sites",`Site ${p.id}`])); registerRoute("/domaines",()=>mount(domainesPage(),["Cockpit","Domaines"])); registerRoute("/pages",()=>mount(pagesPage(),["Cockpit","Pages"])); registerRoute("/modules",()=>mount(modulesPage(),["Cockpit","Modules"])); registerRoute("/medias",()=>mount(mediasPage(),["Cockpit","Médias"])); registerRoute("/seo",()=>mount(seoPage(),["Cockpit","SEO"])); registerRoute("/parametres",()=>mount(parametresPage(),["Cockpit","Paramètres"])); registerRoute("/journal",()=>mount(journalPage(),["Cockpit","Journal"])); registerRoute("/404",()=>mount(notFoundPage(),["Cockpit","Erreur"]));
async function boot(){ const user=await initializeAuth(); setState({user}); try{const status=await getHealth();setState({apiStatus:status});}catch(err){showAlert(err.message,"error");} document.querySelector("#app-header").innerHTML=renderHeader(getState().apiStatus); document.querySelector("#app").setAttribute("aria-busy","false"); const redirect=sessionStorage.getItem("dseRedirect");if(redirect){sessionStorage.removeItem("dseRedirect");location.hash=redirect.includes("#")?redirect.split("#")[1]:"/";} await startRouter(); }
boot();
import { accueilPage } from "../pages/accueil.js";