import { apiGet, apiPost } from "../js/api.js";
export const getMoi = () => apiGet("/moi");
export const getSitesCockpit = (criteres = {}) => apiGet("/cockpit/sites", criteres);
export const getStatutsSite = (domaine) => apiGet("/cockpit/sites/statuts", { domaine });
export const getSiteCockpit = (domaine) => apiGet("/cockpit/site", { domaine });
export const getEdition = (domaine, composant, element = "") => apiGet("/cockpit/edition", { domaine, composant, element });
export const apercuEdition = (domaine, composant, valeurs, element = "") => apiPost("/cockpit/edition/apercu", { domaine, composant, valeurs, element });
export const confirmerEdition = (jeton) => apiPost("/cockpit/edition/confirmer", { jeton });
export const getAdminTableau = () => apiGet("/cockpit/admin/tableau");
export const getAdminUtilisateurs = () => apiGet("/cockpit/admin/utilisateurs");
export const apercuAdmin = (action, params) => apiPost("/cockpit/admin/apercu", { action, params });
export const confirmerAdmin = (jeton) => apiPost("/cockpit/admin/confirmer", { jeton });
export const getIncidents = () => apiGet("/cockpit/incidents");
export const deciderIncident = (incident, decision) => apiPost("/cockpit/incidents/decision", { incident, decision });
